# docker-compose.prod.yml
services:
  backend:
    image: 328307993748.dkr.ecr.sa-east-1.amazonaws.com/gym-backend:latest
    environment:
      - HTTP_PROXY=http://10.0.1.114:8080
      - HTTPS_PROXY=http://10.0.1.114:8080
    restart: always
    networks:
      - gym-network

  frontend:
    image: 328307993748.dkr.ecr.sa-east-1.amazonaws.com/gym-frontend:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge