
services:
  db:
    image: mysql:8.4
    container_name: mysql-prisma
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=gimnasio
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=usuario123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: gym-redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gym-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mysql_data:
    external: true