name: Deploy de GymLab

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Configurar credenciales de AWS
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2. Abrir puerto SSH en el Security Group (Solo para el Runner)
      - name: Agregar IP de GitHub al Security Group
        run: |
          PUBLIC_IP=$(curl -s https://ifconfig.me)
          aws ec2 authorize-security-group-ingress \
            --group-id sg-03f474a5bd0f6527a \
            --protocol tcp \
            --port 22 \
            --cidr ${PUBLIC_IP}/32

      # 3. Construir y subir imágenes a ECR
      - name: Login a Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push
        run: |
          docker build -t 328307993748.dkr.ecr.sa-east-1.amazonaws.com/gym-backend:latest ./backend
          docker push 328307993748.dkr.ecr.sa-east-1.amazonaws.com/gym-backend:latest
          docker build -t 328307993748.dkr.ecr.sa-east-1.amazonaws.com/gym-frontend:latest ./frontend
          docker push 328307993748.dkr.ecr.sa-east-1.amazonaws.com/gym-frontend:latest

      # 4. Copiar docker-compose al servidor del frontend
      - name: Copiar docker-compose al Frontend
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FRONT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose-prod.yaml"
          target: "/home/ubuntu/frontend-produccion"
          strip_components: 0
          overwrite: true

      # 5. Desplegar mediante SSH
      - name: Deploy via SSH Jump
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FRONT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Login en ECR (Frontend)
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 328307993748.dkr.ecr.sa-east-1.amazonaws.com
            
            # 2. Despliegue Frontend
            cd /home/ubuntu/frontend-produccion
            docker compose -f docker-compose-prod.yaml --profile frontend pull
            docker compose -f docker-compose-prod.yaml --profile frontend up -d --remove-orphans
            
            # 3. Configurar llave para el salto al Backend
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/deploy_key
            chmod 600 /tmp/deploy_key
            
            # 4. Copiar el compose al Backend usando la llave temporal
            scp -i /tmp/deploy_key -o StrictHostKeyChecking=no /home/ubuntu/frontend-produccion/docker-compose-prod.yaml ${{ secrets.USER }}@${{ secrets.BACK_IP }}:/home/ubuntu/backend-produccion/docker-compose-prod.yaml
            
            # 5. Ejecutar comandos en el Backend
            ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.BACK_IP }} << 'EOF'
              export http_proxy=http://10.0.1.114:8080
              export https_proxy=http://10.0.1.114:8080
              
              aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 328307993748.dkr.ecr.sa-east-1.amazonaws.com
              
              cd /home/ubuntu/backend-produccion
              docker compose -f docker-compose-prod.yaml --profile backend pull
              docker compose -f docker-compose-prod.yaml --profile backend up -d --remove-orphans
            EOF
            
            # 6. Limpiar la llave temporal
            rm /tmp/deploy_key

      # 6. Cerrar el puerto en el SG
      - name: Eliminar IP de GitHub del Security Group
        if: always()
        run: |
          PUBLIC_IP=$(curl -s https://ifconfig.me)
          aws ec2 revoke-security-group-ingress \
            --group-id sg-03f474a5bd0f6527a \
            --protocol tcp \
            --port 22 \
            --cidr ${PUBLIC_IP}/32